SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

CELL_SIZE = 20
CELLS_IN_WIDTH = SCREEN_WIDTH // CELL_SIZE
CELLS_IN_HEIGHT = SCREEN_HEIGHT // CELL_SIZE


SNAKE_COLOR = (0, 255, 0)
APPLE_COLOR = (255, 0, 0)
TEXT_COLOR = (255, 255, 255)
TEXT_SIZE = SCREEN_WIDTH // 2

