import os

FILE_PATH: str = os.path.dirname(os.path.realpath(__file__)) + "/config.txt"

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 500
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

CELL_SIZE = 20
CELLS_IN_WIDTH = SCREEN_WIDTH // CELL_SIZE
CELLS_IN_HEIGHT = SCREEN_HEIGHT // CELL_SIZE


SNAKE_COLOR = (0, 255, 0, 100)
APPLE_COLOR = (255, 0, 0)
TEXT_COLOR = (255, 255, 255)
TEXT_SIZE = SCREEN_WIDTH // 2

